const data = {
    products: [
      {
        _id: '0',
        name: 'Cherry Tug',
        category: 'Toy',
        image: '/images/cherry-tug.png',
        price: 20,
        brand: 'Bite Me',
        description: 'Play tug with these cute cherries! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel tortor in metus facilisis suscipit ut vel justo. Cras id facilisis massa, vitae blandit augue. Pellentesque enim purus, lobortis in vestibulum et, dictum id orci. Morbi posuere ultricies fermentum. Quisque rhoncus dui erat, vel condimentum felis bibendum at. Cras ac efficitur metus, nec viverra est. Aenean laoreet aliquet molestie. Suspendisse laoreet facilisis diam, ac pellentesque velit. Etiam tempor lorem vel mauris rhoncus, a rutrum lectus bibendum.',
        stock: 20,
      },
      {
        _id: '1',
        name: 'Chocolate Toy',
        category: 'Toy',
        image: '/images/chocolate.png',
        price: 20,
        brand: 'Bite Me',
        description: 'Cutest chocolate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel tortor in metus facilisis suscipit ut vel justo. Cras id facilisis massa, vitae blandit augue. Pellentesque enim purus, lobortis in vestibulum et, dictum id orci. Morbi posuere ultricies fermentum. Quisque rhoncus dui erat, vel condimentum felis bibendum at. Cras ac efficitur metus, nec viverra est. Aenean laoreet aliquet molestie. Suspendisse laoreet facilisis diam, ac pellentesque velit. Etiam tempor lorem vel mauris rhoncus, a rutrum lectus bibendum.',
        stock: 20,
      },
      {
        _id: '2',
        name: 'Gimbap Toy',
        category: 'Toy',
        image: '/images/gimbap.png',
        price: 20,
        brand: 'Bite Me',
        description: 'Yummy Gimbap. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel tortor in metus facilisis suscipit ut vel justo. Cras id facilisis massa, vitae blandit augue. Pellentesque enim purus, lobortis in vestibulum et, dictum id orci. Morbi posuere ultricies fermentum. Quisque rhoncus dui erat, vel condimentum felis bibendum at. Cras ac efficitur metus, nec viverra est. Aenean laoreet aliquet molestie. Suspendisse laoreet facilisis diam, ac pellentesque velit. Etiam tempor lorem vel mauris rhoncus, a rutrum lectus bibendum.',
        stock: 20,
      },
      {
        _id: '3',
        name: 'Lemonade',
        category: 'Toy',
        image: '/images/lemonade.png',
        price: 20,
        brand: 'Bite Me',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel tortor in metus facilisis suscipit ut vel justo. Cras id facilisis massa, vitae blandit augue. Pellentesque enim purus, lobortis in vestibulum et, dictum id orci. Morbi posuere ultricies fermentum. Quisque rhoncus dui erat, vel condimentum felis bibendum at. Cras ac efficitur metus, nec viverra est. Aenean laoreet aliquet molestie. Suspendisse laoreet facilisis diam, ac pellentesque velit. Etiam tempor lorem vel mauris rhoncus, a rutrum lectus bibendum.',
      },
      {
        _id: '4',
        name: 'Loaf',
        category: 'Toy',
        image: '/images/loaf.png',
        price: 20,
        brand: 'Bite Me',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel tortor in metus facilisis suscipit ut vel justo. Cras id facilisis massa, vitae blandit augue. Pellentesque enim purus, lobortis in vestibulum et, dictum id orci. Morbi posuere ultricies fermentum. Quisque rhoncus dui erat, vel condimentum felis bibendum at. Cras ac efficitur metus, nec viverra est. Aenean laoreet aliquet molestie. Suspendisse laoreet facilisis diam, ac pellentesque velit. Etiam tempor lorem vel mauris rhoncus, a rutrum lectus bibendum.',
        stock: 20,
      },
      {
        _id: '5',
        name: 'Meat',
        category: 'Toy',
        image: '/images/meat.png',
        price: 20,
        brand: 'Bite Me',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel tortor in metus facilisis suscipit ut vel justo. Cras id facilisis massa, vitae blandit augue. Pellentesque enim purus, lobortis in vestibulum et, dictum id orci. Morbi posuere ultricies fermentum. Quisque rhoncus dui erat, vel condimentum felis bibendum at. Cras ac efficitur metus, nec viverra est. Aenean laoreet aliquet molestie. Suspendisse laoreet facilisis diam, ac pellentesque velit. Etiam tempor lorem vel mauris rhoncus, a rutrum lectus bibendum.',
        stock: 20,
      },
      {
        _id: '6',
        name: 'Playbook',
        category: 'Toy',
        image: '/images/playbook.png',
        price: 20,
        brand: 'Bite Me',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel tortor in metus facilisis suscipit ut vel justo. Cras id facilisis massa, vitae blandit augue. Pellentesque enim purus, lobortis in vestibulum et, dictum id orci. Morbi posuere ultricies fermentum. Quisque rhoncus dui erat, vel condimentum felis bibendum at. Cras ac efficitur metus, nec viverra est. Aenean laoreet aliquet molestie. Suspendisse laoreet facilisis diam, ac pellentesque velit. Etiam tempor lorem vel mauris rhoncus, a rutrum lectus bibendum.',
        stock: 20,
      },
      {
        _id: '7',
        name: 'Pretzel',
        category: 'Toy',
        image: '/images/pretzel.png',
        price: 20,
        brand: 'Bite Me',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel tortor in metus facilisis suscipit ut vel justo. Cras id facilisis massa, vitae blandit augue. Pellentesque enim purus, lobortis in vestibulum et, dictum id orci. Morbi posuere ultricies fermentum. Quisque rhoncus dui erat, vel condimentum felis bibendum at. Cras ac efficitur metus, nec viverra est. Aenean laoreet aliquet molestie. Suspendisse laoreet facilisis diam, ac pellentesque velit. Etiam tempor lorem vel mauris rhoncus, a rutrum lectus bibendum.',
        stock: 20,
      },
      {
        _id: '8',
        name: 'Rollcake',
        category: 'Toy',
        image: '/images/rollcake.png',
        price: 20,
        brand: 'Bite Me',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel tortor in metus facilisis suscipit ut vel justo. Cras id facilisis massa, vitae blandit augue. Pellentesque enim purus, lobortis in vestibulum et, dictum id orci. Morbi posuere ultricies fermentum. Quisque rhoncus dui erat, vel condimentum felis bibendum at. Cras ac efficitur metus, nec viverra est. Aenean laoreet aliquet molestie. Suspendisse laoreet facilisis diam, ac pellentesque velit. Etiam tempor lorem vel mauris rhoncus, a rutrum lectus bibendum.',
        stock: 20,
      },
      {
        _id: '9',
        name: 'Toast',
        category: 'Toy',
        image: '/images/toast.png',
        price: 20,
        brand: 'Bite Me',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel tortor in metus facilisis suscipit ut vel justo. Cras id facilisis massa, vitae blandit augue. Pellentesque enim purus, lobortis in vestibulum et, dictum id orci. Morbi posuere ultricies fermentum. Quisque rhoncus dui erat, vel condimentum felis bibendum at. Cras ac efficitur metus, nec viverra est. Aenean laoreet aliquet molestie. Suspendisse laoreet facilisis diam, ac pellentesque velit. Etiam tempor lorem vel mauris rhoncus, a rutrum lectus bibendum.',
      },
      {
        _id: '10',
        name: 'Yoooboo Sushi',
        category: 'Toy',
        image: '/images/yooboo.png',
        price: 20,
        brand: 'Bite Me',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel tortor in metus facilisis suscipit ut vel justo. Cras id facilisis massa, vitae blandit augue. Pellentesque enim purus, lobortis in vestibulum et, dictum id orci. Morbi posuere ultricies fermentum. Quisque rhoncus dui erat, vel condimentum felis bibendum at. Cras ac efficitur metus, nec viverra est. Aenean laoreet aliquet molestie. Suspendisse laoreet facilisis diam, ac pellentesque velit. Etiam tempor lorem vel mauris rhoncus, a rutrum lectus bibendum.',
        stock: 20,
      },
      {
        _id: '11',
        name: 'Clam & Pearl',
        category: 'Toy',
        image: '/images/clam.png',
        price: 20,
        brand: 'Bite Me',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel tortor in metus facilisis suscipit ut vel justo. Cras id facilisis massa, vitae blandit augue. Pellentesque enim purus, lobortis in vestibulum et, dictum id orci. Morbi posuere ultricies fermentum. Quisque rhoncus dui erat, vel condimentum felis bibendum at. Cras ac efficitur metus, nec viverra est. Aenean laoreet aliquet molestie. Suspendisse laoreet facilisis diam, ac pellentesque velit. Etiam tempor lorem vel mauris rhoncus, a rutrum lectus bibendum.',
        stock: 20,
      }
    ]
  }
  
  export default data;