const data = {
  products: [
    {
      _id: '1',
      name: 'Cherry Tug',
      category: 'Toy',
      image: '/images/cherry-tug.png',
      price: 20,
      brand: 'Bite Me',
      description: 'Play tug with these cute cherries!',
    },
    {
      _id: '2',
      name: 'Chocolate Toy',
      category: 'Toy',
      image: '/images/chocolate.png',
      price: 20,
      brand: 'Bite Me',
      description: 'Cutest chocolate',
    },
    {
      _id: '3',
      name: 'Gimbap Toy',
      category: 'Toy',
      image: '/images/gimbap.png',
      price: 20,
      brand: 'Bite Me',
      description: 'Yummy Gimbap',
    },
    {
      _id: '4',
      name: 'Lemonade',
      category: 'Toy',
      image: '/images/lemonade.png',
      price: 20,
      brand: 'Bite Me',
      description: 'Lemonade',
    },
    {
      _id: '5',
      name: 'Loaf',
      category: 'Toy',
      image: '/images/loaf.png',
      price: 20,
      brand: 'Bite Me',
      description: 'Cutest chocolate',
    },
    {
      _id: '6',
      name: 'Meat',
      category: 'Toy',
      image: '/images/meat.png',
      price: 20,
      brand: 'Bite Me',
      description: 'Cutest chocolate',
    },
    {
      _id: '7',
      name: 'Playbook',
      category: 'Toy',
      image: '/images/playbook.png',
      price: 20,
      brand: 'Bite Me',
      description: 'Cutest chocolate',
    },
    {
      _id: '8',
      name: 'Pretzel',
      category: 'Toy',
      image: '/images/pretzel.png',
      price: 20,
      brand: 'Bite Me',
      description: 'Cutest chocolate',
    },
    {
      _id: '9',
      name: 'Rollcake',
      category: 'Toy',
      image: '/images/rollcake.png',
      price: 20,
      brand: 'Bite Me',
      description: 'Cutest chocolate',
    },
    {
      _id: '10',
      name: 'Toast',
      category: 'Toy',
      image: '/images/toast.png',
      price: 20,
      brand: 'Bite Me',
      description: 'Cutest chocolate',
    },
    {
      _id: '11',
      name: 'Yoooboo Sushi',
      category: 'Toy',
      image: '/images/yooboo.png',
      price: 20,
      brand: 'Bite Me',
      description: 'Cutest chocolate',
    },
    {
      _id: '12',
      name: 'Clam & Pearl',
      category: 'Toy',
      image: '/images/clam.png',
      price: 20,
      brand: 'Bite Me',
      description: 'Cutest chocolate',
    }
  ]
}

export default data;